
word = ["apple", "banana", "orange", "grape", "mango", "peach", "pear", "plum", "cherry", "melon",
"computer", "keyboard", "mouse", "monitor", "printer", "laptop", "tablet", "phone", "camera", "speaker",
"python", "java", "coding", "program", "function", "variable", "string", "integer", "boolean", "loop",
"school", "college", "student", "teacher", "classroom", "library", "subject", "lesson", "exam", "project",
"river", "mountain", "forest", "ocean", "desert", "island", "valley", "waterfall", "beach", "garden",
"table", "chair", "window", "door", "floor", "ceiling", "mirror", "pillow", "blanket", "curtain",
"football", "cricket", "tennis", "hockey", "basketball", "volleyball", "badminton", "running", "cycling", "swimming",
"doctor", "engineer", "scientist", "artist", "writer", "designer", "chef", "pilot", "farmer", "lawyer",
"music", "guitar", "piano", "violin", "drum", "flute", "dance", "painting", "drawing", "singing",
"happy", "bright", "strong", "clever", "honest", "kind", "brave", "gentle", "silent", "quick","rocket", "planet", "galaxy", "comet", "asteroid", "satellite", "telescope", "universe", "gravity", "orbit",
"bottle", "bucket", "plate", "spoon", "fork", "knife", "glass", "cup", "kettle", "pan",
"shirt", "pants", "jacket", "sweater", "scarf", "gloves", "socks", "shoes", "sandals", "hat",
"lion", "tiger", "elephant", "giraffe", "zebra", "monkey", "rabbit", "horse", "donkey", "camel",
"parrot", "eagle", "sparrow", "pigeon", "owl", "crow", "peacock", "penguin", "flamingo", "swan",
"carrot", "potato", "onion", "tomato", "cabbage", "broccoli", "spinach", "lettuce", "cucumber", "pepper",
"bread", "butter", "cheese", "milk", "coffee", "tea", "juice", "cookie", "biscuit", "sandwich",
"clock", "calendar", "notebook", "pencil", "eraser", "marker", "folder", "backpack", "calculator", "dictionary",
"bridge", "airport", "station", "highway", "village", "city", "country", "museum", "hospital", "market",
"energy", "success", "freedom", "wisdom", "courage", "patience", "respect", "friendship", "knowledge", "imagination","diamond", "gold", "silver", "copper", "iron", "steel", "bronze", "platinum", "crystal", "marble",
"circle", "square", "triangle", "rectangle", "polygon", "sphere", "cube", "cylinder", "cone", "pyramid",
"spring", "summer", "autumn", "winter", "morning", "afternoon", "evening", "midnight", "sunrise", "sunset",
"rain", "storm", "cloud", "thunder", "lightning", "snow", "hail", "breeze", "hurricane", "tornado",
"engine", "battery", "wheel", "brake", "mirror", "helmet", "bicycle", "motorcycle", "truck", "tractor",
"bridge", "tunnel", "building", "apartment", "office", "factory", "warehouse", "temple", "mosque", "church",
"internet", "website", "browser", "network", "server", "database", "algorithm", "software", "hardware", "compiler",
"password", "username", "security", "firewall", "encryption", "download", "upload", "backup", "storage", "memory",
"vacation", "journey", "adventure", "exploration", "destination", "passport", "luggage", "ticket", "tourist", "guide",
"victory", "failure", "challenge", "opportunity", "confidence", "discipline", "motivation", "creativity", "curiosity", "leadership"]